### ISSUE TITLE
SIGSEGV occurs in pocketbase v0.23.9 on linux_armv7

### ISSUE THREAD

**Issue by zuizui-kuroiko** [pocketbase/pocketbase#6136] opened 2024-12-18 07:48 UTC
The v0.23.9 release, which included the fix for #6132, causes the linux_armv7 executable to terminate with a SIGSEGV after approximately 30 minutes of runtime every time.

This issue occurs both when migrating pb_data from v0.22.x, and also when starting a new instance with v0.23.9 **without** using existing pb_data.

The log output is as follows:
```
unexpected fault address 0x1d378646
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1d378646 pc=0xaaab68]

goroutine 493 gp=0x3c9e5a8 m=2 mp=0x3466508 [running]:
runtime.throw({0x133981e, 0x5})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:1067 +0x34 fp=0x390fe04 sp=0x390fdf0 pc=0x8d4c8
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/signal_unix.go:931 +0x2a4 fp=0x390fe34 sp=0x390fe04 pc=0x8f7dc
modernc.org/memory.(*Allocator).UintptrFree(0x25c24a8, 0x76418290)
        /home/runner/go/pkg/mod/modernc.org/memory@v1.8.0/memory.go:222 +0x140 fp=0x390fe4c sp=0x390fe38 pc=0xaaab68
modernc.org/libc.Xfree(0x34a4360, 0x76418290)
        /home/runner/go/pkg/mod/modernc.org/libc@v1.61.4/mem_musl.go:99 +0x60 fp=0x390fe70 sp=0x390fe4c pc=0xabe860
modernc.org/libc.(*TLS).Close(0x34a4360)
        /home/runner/go/pkg/mod/modernc.org/libc@v1.61.4/libc_musl.go:470 +0xf4 fp=0x390fe9c sp=0x390fe70 pc=0xabde84
modernc.org/sqlite.(*conn).Close(0x36940e0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:1469 +0xb4 fp=0x390fec4 sp=0x390fe9c pc=0xca989c
database/sql.(*driverConn).finalClose.func2()
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:687 +0x3c fp=0x390fedc sp=0x390fec4 pc=0x3b526c
database/sql.withLock({0x1a479e8, 0x34a43c0}, 0x4294738)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:3566 +0x6c fp=0x390fef8 sp=0x390fedc pc=0x3c24c0
database/sql.(*driverConn).finalClose(0x34a43c0)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:685 +0xdc fp=0x390ff50 sp=0x390fef8 pc=0x3b5114
database/sql.finalCloser.finalClose-fm()
        <autogenerated>:1 +0x30 fp=0x390ff60 sp=0x390ff50 pc=0x3c3d44
database/sql.(*driverConn).Close(0x34a43c0)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:666 +0xfc fp=0x390ff84 sp=0x390ff60 pc=0x3b5000
database/sql.(*DB).connectionCleaner(0x37166e8, 0x29e8d60800)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1113 +0x320 fp=0x390ffdc sp=0x390ff84 pc=0x3b718c
database/sql.(*DB).startCleanerLocked.gowrap1()
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1083 +0x38 fp=0x390ffec sp=0x390ffdc pc=0x3b6e40
runtime.goexit({})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/asm_arm.s:884 +0x4 fp=0x390ffec sp=0x390ffec pc=0x94de8
created by database/sql.(*DB).startCleanerLocked in goroutine 488
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1083 +0x20c
```

**Comment by ganigeorgiev** [comment] 2024-12-18 08:15
Could you start the executable with `--dev` and report back the printed query logs right before the error?

**Comment by zuizui-kuroiko** [comment] 2024-12-18 09:32
## pocketbase v0.23.9 (Executable file downloaded from github)
- Start with `--dev` parameter
- SIGSEGV occurs after about 30 minutes of execution
- After starting, leave it until an error occurs
  - The previous `SELECT COUNT` sql statement should not be the cause of the error.

The log output is as follows:
```
$ ./pocketbase serve --dev --http 0.0.0.0:8787
[157.00ms] CREATE TABLE IF NOT EXISTS `_migrations` (file VARCHAR(255) PRIMARY KEY NOT NULL, applied INTEGER NOT NULL)
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1640988000_aux_init.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1640988000_init.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233556_v0.23_migrate.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233557_v0.23_migrate2.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233558_v0.23_migrate3.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233559_v0.23_migrate4.go' LIMIT 1
[5.00ms] SELECT `_collections`.* FROM `_collections` ORDER BY `created` ASC
[1.00ms] SELECT `_params`.* FROM `_params` WHERE `id`='settings'
[1.00ms] SELECT `_collections`.* FROM `_collections` ORDER BY `created` ASC
[4.00ms] CREATE TABLE IF NOT EXISTS `_migrations` (file VARCHAR(255) PRIMARY KEY NOT NULL, applied INTEGER NOT NULL)
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1640988000_aux_init.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1640988000_init.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233556_v0.23_migrate.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233557_v0.23_migrate2.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233558_v0.23_migrate3.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1717233559_v0.23_migrate4.go' LIMIT 1
[0.00ms] SELECT count(*) FROM `_migrations` WHERE `file`='1734477336_created_test_.js' LIMIT 1
2024/12/18 17:27:58 Server started at http://0.0.0.0:8787
├─ REST API:  http://0.0.0.0:8787/api/
└─ Dashboard: http://0.0.0.0:8787/_/
[1.00ms] SELECT count(*) FROM `_superusers` WHERE NOT (`email`='__pbinstaller@example.com')
INFO GET /api/collections/_superusers/auth-methods?fields=mfa,otp,password,oauth2
[1.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `email`='zuizui.kuroiko@gmail.com' LIMIT 1
[0.00ms] SELECT `_authOrigins`.* FROM `_authOrigins` WHERE `collectionRef`='pbc_3142635823' AND `recordRef`='b009q3301imic8v' ORDER BY `created` DESC
[0.00ms] SELECT `_collections`.* FROM `_collections` WHERE `id`='pbc_3142635823'
[0.00ms] SELECT (1) FROM `_superusers` WHERE `id`='b009q3301imic8v' LIMIT 1
[4.00ms] UPDATE `_authOrigins` SET `collectionRef`='pbc_3142635823', `created`='2024-12-17 23:15:09.262Z', `fingerprint`='698e3eb94a2459b2fbe58e6b0b70a340', `id`='4ypi9r21j4emzi1', `recordRef`='b009q3301imic8v', `updated`='2024-12-18 08:28:30.328Z' WHERE `id`='4ypi9r21j4emzi1'
[1.00ms] SELECT `_authOrigins`.* FROM `_authOrigins` WHERE `_authOrigins`.`id`='4ypi9r21j4emzi1' LIMIT 1
INFO POST /api/collections/_superusers/auth-with-password
[0.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
INFO GET /api/settings
[0.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[0.00ms] SELECT `_collections`.* FROM `_collections` ORDER BY `name` ASC LIMIT 200
INFO GET /api/collections?page=1&perPage=200&skipTotal=1&sort=+name
[0.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[0.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[2.00ms] SELECT `users`.* FROM `users` LIMIT 1
INFO GET /api/collections/meta/scaffolds
[10.00ms] SELECT COUNT(DISTINCT `users`.`id`) FROM `users`
INFO GET /api/collections/_pb_users_auth_/records?page=1&perPage=1&filter=&fields=id
[0.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[0.00ms] SELECT `users`.* FROM `users` ORDER BY `users`.`_rowid_` DESC LIMIT 40
INFO GET /api/collections/_pb_users_auth_/records?page=1&perPage=40&sort=-@rowid&skipTotal=1&filter=&expand=&fields=
[1.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[1.00ms] SELECT `_superusers`.* FROM `_superusers` WHERE `_superusers`.`id`='b009q3301imic8v' LIMIT 1
[0.00ms] SELECT `test`.* FROM `test` LIMIT 1
[1.00ms] SELECT `test`.* FROM `test` ORDER BY `test`.`_rowid_` DESC LIMIT 40
INFO GET /api/collections/pbc_4285667772/records?page=1&perPage=40&sort=-@rowid&skipTotal=1&filter=&expand=&fields=
[12.00ms] SELECT COUNT(DISTINCT `test`.`id`) FROM `test`
INFO GET /api/collections/pbc_4285667772/records?page=1&perPage=1&filter=&fields=id

unexpected fault address 0x370d5215
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x370d5215 pc=0xbdb3a8]

goroutine 213 gp=0x2cb8c68 m=7 mp=0x2888a08 [running]:
runtime.throw({0x133981e, 0x5})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/panic.go:1067 +0x34 fp=0x2a808b0 sp=0x2a8089c pc=0x8d4c8
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/signal_unix.go:931 +0x2a4 fp=0x2a808e0 sp=0x2a808b0 pc=0x8f7dc
modernc.org/sqlite/lib._selectExpander(0x28aa120, 0x75900710, 0x76307998)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:128987 +0x95c fp=0x2a80a54 sp=0x2a808e4 pc=0xbdb3a8
modernc.org/sqlite/lib._sqlite3WalkSelect(0x28aa120, 0x75900710, 0x76307998)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:82917 +0x70 fp=0x2a80a6c sp=0x2a80a54 pc=0xb5f76c
modernc.org/sqlite/lib._sqlite3SelectExpand(0x28aa120, 0x75b01010, 0x76307998)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:129266 +0x128 fp=0x2a80ab4 sp=0x2a80a6c pc=0xbdc708
modernc.org/sqlite/lib._sqlite3SelectPrep(0x28aa120, 0x75b01010, 0x76307998, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:129361 +0x50 fp=0x2a80ac8 sp=0x2a80ab4 pc=0xbdca50
modernc.org/sqlite/lib._sqlite3Select(0x28aa120, 0x75b01010, 0x76307998, 0x75900618)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:130396 +0x1c8 fp=0x2a80c94 sp=0x2a80ac8 pc=0xbdf3ac
modernc.org/sqlite/lib._yy_reduce(0x28aa120, 0x75b01814, 0x54, 0x1, {0x76307660, 0x0}, 0x75b01010)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:162509 +0x120c fp=0x2a80d60 sp=0x2a80c94 pc=0xc1ea90
modernc.org/sqlite/lib._sqlite3Parser(0x28aa120, 0x75b01814, 0x1, {0x76307660, 0x0})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:163932 +0xa8 fp=0x2a80da0 sp=0x2a80d60 pc=0xc249c4
modernc.org/sqlite/lib._sqlite3RunParser(0x28aa120, 0x75b01010, 0x76307618)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:166613 +0x338 fp=0x2a80e18 sp=0x2a80da0 pc=0xc264dc
modernc.org/sqlite/lib._sqlite3Prepare(0x28aa120, 0x75d00018, 0x76307618, 0xffffffff, 0x0, 0x0, 0x75d01010, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122340 +0x368 fp=0x2a80e64 sp=0x2a80e18 pc=0xbc9d9c
modernc.org/sqlite/lib._sqlite3LockAndPrepare(0x28aa120, 0x75d00018, 0x76307618, 0xffffffff, 0x0, 0x0, 0x75d01010, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122402 +0x158 fp=0x2a80ea8 sp=0x2a80e64 pc=0xbca2fc
modernc.org/sqlite/lib.Xsqlite3_prepare(0x28aa120, 0x75d00018, 0x76307618, 0xffffffff, 0x75d01010, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122488 +0x54 fp=0x2a80ed0 sp=0x2a80ea8 pc=0xbca6fc
modernc.org/sqlite/lib._loadStatTbl(0x28aa120, 0x75d00018, 0x1470fe7, 0x147102c, 0x146fb29)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:97845 +0x11c fp=0x2a80f40 sp=0x2a80ed0 pc=0xb8937c
modernc.org/sqlite/lib._loadStat4(0x28aa120, 0x75d00018, 0x146fb29)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:97986 +0xc4 fp=0x2a80f60 sp=0x2a80f40 pc=0xb89c34
modernc.org/sqlite/lib._sqlite3AnalysisLoad(0x28aa120, 0x75d00018, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:98086 +0x33c fp=0x2a80fc4 sp=0x2a80f60 pc=0xb89fa0
modernc.org/sqlite/lib._sqlite3InitOne(0x28aa120, 0x75d00018, 0x0, 0x75d00814, 0x0)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:121880 +0x7a4 fp=0x2a81044 sp=0x2a80fc4 pc=0xbc906c
modernc.org/sqlite/lib._sqlite3Init(0x28aa120, 0x75d00018, 0x75d00814)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:121950 +0x70 fp=0x2a81068 sp=0x2a81044 pc=0xbc925c
modernc.org/sqlite/lib._sqlite3ReadSchema(0x28aa120, 0x75d00810)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:121993 +0x50 fp=0x2a81080 sp=0x2a81068 pc=0xbc9398
modernc.org/sqlite/lib._sqlite3Pragma(0x28aa120, 0x75d00810, 0x75b00840, 0x75b0084c, 0x75b00864, 0x1)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:118538 +0x424 fp=0x2a814dc sp=0x2a81080 pc=0xbbfbf8
modernc.org/sqlite/lib._yy_reduce(0x28aa120, 0x75b00814, 0x101, 0x1, {0x75f00589, 0x0}, 0x75d00810)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:163425 +0x5634 fp=0x2a815a8 sp=0x2a814dc pc=0xc22eb8
modernc.org/sqlite/lib._sqlite3Parser(0x28aa120, 0x75b00814, 0x1, {0x75f00589, 0x0})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:163932 +0xa8 fp=0x2a815e8 sp=0x2a815a8 pc=0xc249c4
modernc.org/sqlite/lib._sqlite3RunParser(0x28aa120, 0x75d00810, 0x75f00570)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:166613 +0x338 fp=0x2a81660 sp=0x2a815e8 pc=0xc264dc
modernc.org/sqlite/lib._sqlite3Prepare(0x28aa120, 0x75d00018, 0x75f00570, 0xffffffff, 0x80, 0x0, 0x76100010, 0x76100018)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122340 +0x368 fp=0x2a816ac sp=0x2a81660 pc=0xbc9d9c
modernc.org/sqlite/lib._sqlite3LockAndPrepare(0x28aa120, 0x75d00018, 0x75f00570, 0xffffffff, 0x80, 0x0, 0x76100010, 0x76100018)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122402 +0x158 fp=0x2a816f0 sp=0x2a816ac pc=0xbca2fc
modernc.org/sqlite/lib.Xsqlite3_prepare_v2(0x28aa120, 0x75d00018, 0x75f00570, 0xffffffff, 0x76100010, 0x76100018)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/lib/sqlite_linux_arm.go:122501 +0x54 fp=0x2a81718 sp=0x2a816f0 pc=0xbca768
modernc.org/sqlite.(*conn).prepareV2(0x2908600, 0x2a81784)
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:1311 +0x14c fp=0x2a81758 sp=0x2a81718 pc=0xca8bc0
modernc.org/sqlite.(*stmt).exec(0x2a6e0a8, {0x1a4d674, 0x25cd5e0}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:525 +0x1f8 fp=0x2a817b4 sp=0x2a81758 pc=0xca4fd8
modernc.org/sqlite.(*conn).exec(0x2908600, {0x1a4d674, 0x25cd5e0}, {0x2a8182c, 0x19}, {0x0, 0x0, 0x0})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:1726 +0xe8 fp=0x2a817f8 sp=0x2a817b4 pc=0xca9f34
modernc.org/sqlite.applyQueryParams(0x2908600, {0x2cb6010, 0xc6})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:908 +0x264 fp=0x2a81964 sp=0x2a817f8 pc=0xca7014
modernc.org/sqlite.newConn({0x2cb6000, 0xd6})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:857 +0x1f8 fp=0x2a819b4 sp=0x2a81964 pc=0xca6a9c
modernc.org/sqlite.(*Driver).Open(0x25c12e0, {0x2cb6000, 0xd6})
        /home/runner/go/pkg/mod/modernc.org/sqlite@v1.34.2/sqlite.go:1994 +0x24 fp=0x2a81a24 sp=0x2a819b4 pc=0xcaaf88
database/sql.dsnConnector.Connect(...)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:801
database/sql.(*dsnConnector).Connect(0x2cae780, {0x1a4d790, 0x2c24000})
        <autogenerated>:1 +0x4c fp=0x2a81a44 sp=0x2a81a24 pc=0x3c3778
database/sql.(*DB).conn(0x2ca9728, {0x1a4d790, 0x2c24000}, 0x1)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1423 +0x808 fp=0x2a81b34 sp=0x2a81a44 pc=0x3b8818
database/sql.(*DB).query(0x2ca9728, {0x1a4d790, 0x2c24000}, {0x2b46120, 0x51}, {0x2a6e080, 0x1, 0x1}, 0x1)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1751 +0x34 fp=0x2a81b78 sp=0x2a81b34 pc=0x3baa1c
database/sql.(*DB).QueryContext.func1(0x1)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1734 +0x6c fp=0x2a81bb4 sp=0x2a81b78 pc=0x3ba8e8
database/sql.(*DB).retry(0x2ca9728, 0x2a81bfc)
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1568 +0x78 fp=0x2a81bdc sp=0x2a81bb4 pc=0x3b9540
database/sql.(*DB).QueryContext(0x2ca9728, {0x1a4d790, 0x2c24000}, {0x2b46120, 0x51}, {0x2a6e080, 0x1, 0x1})
        /opt/hostedtoolcache/go/1.23.4/x64/src/database/sql/sql.go:1733 +0x9c fp=0x2a81c28 sp=0x2a81bdc pc=0x3ba844
github.com/pocketbase/dbx.(*Query).Rows(0x28aa0c0)
        /home/runner/go/pkg/mod/github.com/pocketbase/dbx@v1.11.0/query.go:343 +0x174 fp=0x2a81cfc sp=0x2a81c28 pc=0xa15040
github.com/pocketbase/dbx.(*SelectQuery).All.(*Query).All.func1()
        /home/runner/go/pkg/mod/github.com/pocketbase/dbx@v1.11.0/query.go:280 +0x30 fp=0x2a81d28 sp=0x2a81cfc pc=0xa1ac80
github.com/pocketbase/pocketbase/core.(*BaseApp).modelQuery.func1.execLockRetry.1.2(0x1)
        /home/runner/work/pocketbase/pocketbase/core/db_retry.go:33 +0x1c fp=0x2a81d34 sp=0x2a81d28 pc=0xd14dc4
github.com/pocketbase/pocketbase/core.baseLockRetry(0x2a81db8, 0xc)
        /home/runner/work/pocketbase/pocketbase/core/db_retry.go:47 +0x40 fp=0x2a81d60 sp=0x2a81d34 pc=0xd17f20
github.com/pocketbase/pocketbase/core.(*BaseApp).modelQuery.func1.execLockRetry.1(0x28aa0c0, 0x2cae030)
        /home/runner/work/pocketbase/pocketbase/core/db_retry.go:32 +0xe0 fp=0x2a81dc4 sp=0x2a81d60 pc=0xd14c40
github.com/pocketbase/dbx.(*Query).execWrap(0x28aa0c0, 0x2cae030)
        /home/runner/go/pkg/mod/github.com/pocketbase/dbx@v1.11.0/query.go:364 +0x34 fp=0x2a81dd8 sp=0x2a81dc4 pc=0xa1567c
github.com/pocketbase/dbx.(*Query).All(...)
        /home/runner/go/pkg/mod/github.com/pocketbase/dbx@v1.11.0/query.go:279
github.com/pocketbase/dbx.(*SelectQuery).All(0x2c8e008, {0x116dd38, 0x2cae000})
        /home/runner/go/pkg/mod/github.com/pocketbase/dbx@v1.11.0/select.go:378 +0x138 fp=0x2a81df8 sp=0x2a81dd8 pc=0xa1ac1c
github.com/pocketbase/pocketbase/core.(*BaseApp).FindAllCollections(0x2a7c348, {0x2863788, 0x1, 0x1})
        /home/runner/work/pocketbase/pocketbase/core/collection_query.go:40 +0x31c fp=0x2a81ebc sp=0x2a81df8 pc=0xd07c64
github.com/pocketbase/pocketbase/core.(*BaseApp).DeleteExpiredOTPs(0x2a7c348)
        /home/runner/work/pocketbase/pocketbase/core/otp_query.go:86 +0x44 fp=0x2a81fa8 sp=0x2a81ebc pc=0xd3a1dc
github.com/pocketbase/pocketbase/core.(*BaseApp).registerOTPHooks.func1()
        /home/runner/work/pocketbase/pocketbase/core/otp_model.go:123 +0x20 fp=0x2a81fec sp=0x2a81fa8 pc=0xd39478
runtime.goexit({})
        /opt/hostedtoolcache/go/1.23.4/x64/src/runtime/asm_arm.s:884 +0x4 fp=0x2a81fec sp=0x2a81fec pc=0x94de8
created by github.com/pocketbase/pocketbase/tools/cron.(*Cron).runDue in goroutine 86
        /home/runner/work/pocketbase/pocketbase/tools/cron/cron.go:203 +0x288
```

## pocketbase v0.23.9 build with `modernc.org/sqlite` v1.32.0
- Start with `--dev` parameter
- It has been an hour since the execution but SIGSEGV has not occurred
  - I'll leave it like this and contact you if an error occurs.

**Comment by ganigeorgiev** [comment] 2024-12-18 09:57
Thanks for the logs.

Yes, the COUNT query shouldn't be the cause of the error. Something else is going on here.

I left my instance to run for a little more than an hour but I'm not able to trigger the error while running the arm executable with QUEMU. I've also tried executing periodic read/write requests per 3mins against a dummy test collection but to no avail. The automated tests also seems to run fine with QUEMU (_although significantly slower, bit this is probably because of the emulator_).

It is very likely the above panic to be related to `modernc.org/sqlite` because PocketBase itself doesn't have any `unsafe` calls to trigger such memory address errors.

The main problem is that I'm not sure how to reproduce it and eventually isolate it to submit an issue in the upstream library.

Recently a fix for `disk io` error that could affect arm64 devices was submitted in https://gitlab.com/cznic/sqlite/-/commit/7f15e6eb45fa87fd65c5817b56d449a3b80a1d24 that I'm waiting to get tagged and I noticed the comment that the `libc` dependency was downgraded to v1.55.3 while in our go.mod it is v1.61.4 so maybe it is possible to be another runtime libc peculiarity.

If you have the time, could you try to build with `modernc.org/sqlite` v1.34.2 but also with `modernc.org/libc` v1.55.3 and see if it will crash again (_our go.mod transitive versions should usually match anyway with the `modernc.org/sqlite` ones and I'll update it once the above arm64 fix is tagged_)?

**Comment by ganigeorgiev** [comment] 2024-12-18 17:01
I suspect that this error is caused by the mismatched `modernc.org/libc` indirect dependency version.

If you find time please test it again with the PocketBase [v0.23.10](https://github.com/pocketbase/pocketbase/releases/tag/v0.23.10) binary (it uses `modernc.org/sqlite` v1.34.2 and `modernc.org/libc` v1.55.3).

I'll leave the issue open for now for better visibility.

**Comment by zuizui-kuroiko** [comment] 2024-12-18 21:13
Thank you for the update to v0.23.10. I will check it out.

Following your previous advice, I continued to test after my last reply.
I also suspect that modernc.org/libc might be the culprit.

Test results

## pocketbase v0.23.9 build with sqlite v1.32.0 & libc v1.61.4
- This is the combination I reported as still working last time.
- A SIGSEGV occurred approximately 1.5 hours after startup.
## pocketbase v0.23.9 build with sqlite v1.32.0 & libc v1.55.3
- It has been working fine for over 10 hours now.
## pocketbase v0.23.9 build with sqlite v1.34.2 & libc v1.55.3
- It has been working fine for over 10 hours now.

**Comment by zuizui-kuroiko** [comment] 2024-12-20 02:30
I've been running v0.23.10 on linux_armv7 (32bit) for about a day using pb_data migrated from v0.22.27, and it seems to be stable. 

Thanks for your help.

**Comment by ganigeorgiev** [comment] 2024-12-20 05:51
Thank you for the tests.

The situation with the libc versioning is a little unfortunate but the maintainer has its reasons against semantic versioning it - https://gitlab.com/cznic/sqlite/-/issues/177#note_1807373538

I'll close the issue for now but will consider adding a note about the libc version with each release note to warn against versions mismatch that could result from running `go get -u` or other similar commands.

**Closed by ganigeorgiev** 2024-12-20 05:51 UTC

**Comment by ganigeorgiev** [comment] 2024-12-20 10:24
_Just for info in case someone stumble here: I've added semi-automated checks via [`debug.ReadBuildInfo`](https://pkg.go.dev/runtime/debug@master#ReadBuildInfo) for the expected modernc deps versions to make it more clear in case of accidental versions bump. The warning will be available with the next minor release._
