### ISSUE TITLE
Bug - paths

### ISSUE THREAD

**Issue by pietru2004** [pocketbase/pocketbase#3606] opened 2023-10-25 21:14 UTC
if you use
```
const utils = require(`${__hooks}/utils.js`)
```
on linux it works fine, but if you use the same on windows it stops working and returns
```
{
  "errorMessage": "GoError: Invalid module at github.com/dop251/goja_nodejs/require.(*RequireModule).require-fm (native)"
}
```
cause windows uses `\` and linux `/`

**Comment by ganigeorgiev** [comment] 2023-10-25 21:19
I believe this was resolved in https://github.com/pocketbase/pocketbase/issues/3163.

What version of PocketBase do you use?

**Comment by pietru2004** [comment] 2023-10-25 21:27
latest - ver 0.19

**Comment by ganigeorgiev** [comment] 2023-10-25 21:54
Just tested it Windows 10VM and it works fine for me with PocketBase v0.19.0 and the following setup:

```js
// pb_hooks/main.pb.js
onAfterBootstrap((e) => {
    const utils = require(`${__hooks}/utils.js`);

    utils.hello("world")
})
```

Where `utils.js` is:

```js
// pb_hooks/utils.js
module.exports = {
    hello: (name) => {
        console.log("Hello " + name)
    }
}
```

If you have a custom Go binary double check the goja_nodejs deps in your `go.mod` file is the same as https://github.com/pocketbase/pocketbase/blob/94253f0dd5431e6a5676432537182bd2b0f2adae/go.mod#L11.

**Closed by ganigeorgiev** 2023-10-25 21:54 UTC

**Comment by pietru2004** [comment] 2023-10-25 22:01
I just run basic pocketbase extended with modules

**Comment by pietru2004** [comment] 2023-10-25 22:02
Gona do mrp when I get while

**Comment by pietru2004** [comment] 2023-10-26 04:39
Also I should probably add it is module trying to load module

**Comment by ganigeorgiev** [comment] 2023-10-26 07:09
I don't understand what do you mean. Please provide a **minimal** reproducible repo OR to rule out PocketBase issue - try to reproduce it with the files provided in the comment above https://github.com/pocketbase/pocketbase/issues/3606#issuecomment-1780109970.

**Comment by pietru2004** [comment] 2023-10-26 10:23
I have module called core that is called from add route events
main.pb.js
core.js
utils.js

main.pb.js loads core.js module
core.js module loads utils.js module

**Comment by pietru2004** [comment] 2023-10-26 10:24
I have module called core that is called from add route events
main.pb.js
core.js
utils.js

main.pb.js loads core.js module
core.js module loads utils.js module

**Comment by pietru2004** [comment] 2023-10-26 10:26
```// pb_hooks/main.pb.js
onAfterBootstrap((e) => {
    const core = require(`${__hooks}/core.js`);

    core.hello("world")
})

// pb_hooks/core.js
module.exports = {
    hello: (name) => {
        const utils = require(`${__hooks}/utils.js`);

    utils.hello("world")
    }
}

// pb_hooks/utils.js
module.exports = {
    hello: (name) => {
        console.log("Hello " + name)
    }
}```

**Comment by ganigeorgiev** [comment] 2023-10-26 11:14
What Windows do you use?
Does a single module works in your case?

But in any case, it is most likely an issue in the upstream, I just don't know what exactly is as I'm not able to reproduce it. I'll try to test it again sometime later as using the Windows VM is very cumbersome and hard to debug.

If the above represents a blocker, you can try to:
- make sure that the files has proper read and write permissions
- make sure that there are no typos in the file names
- use relative path in the sub module, aka. `require("./utils.js")`
- replace:
  ```js
  require(`${__hooks}/core.js`)  -> require($filesistem.join(__hooks, "core.js"));
  require(`${__hooks}/utils.js`) -> require($filesistem.join(__hooks, "utils.js"));
  ```
  (_[`$filesistem.join`](https://pocketbase.io/jsvm/functions/_filepath.join.html) is usually the cross-platform safe way to concatenate paths in Go_)

**Comment by ganigeorgiev** [comment] 2023-10-26 12:08
By looking at the `goja_nodejs` code I think I can see why a submodule may not work due to the mixed path-filepath usage (the first one doesn't normalize the os specific separators) and the [resolve.getCurrentModulePath() method](https://github.com/dop251/goja_nodejs/blob/5c1f9037c9ab18d7fd46bc46aaf8859f13d63716/require/resolve.go#L197).

Technically when you have `require(module)` the `module` argument is not treated as regular os filepath and in earlier Node versions absolute Windows paths weren't supported at all (_even now in the [module resolution docs](https://nodejs.org/api/modules.html#file-modules) Windows path are not mentioned_). So I'm not sure if that needs actually to be fixed on the goja_nodejs side OR to just change the `__hooks` PocketBase global var to be a relative path.

I'll think a little more on it this (_or the next following_)  weekend, but in the meanwhile you can try the above mentioned workarounds.

**Comment by pietru2004** [comment] 2023-10-26 14:05
Anyway I have 2 systems it works on linux, windows is 10, I can use docker container to overcome this problem on windows
