### ISSUE TITLE
View changes are not triggering the cascade operation when part of a relation

### ISSUE THREAD

**Issue by McBucek** [pocketbase/pocketbase#3000] opened 2023-07-26 12:05 UTC
After I delete an item from Base Collection, it doesnt delete a relation id string in a record that is connected to View Collection based on the Base Collection of the deleted item

**Example:**
Base Collection A, Base Collection B and ViewCollection C based on B (contains extracted data from B).
A has some relations to records from B and some relations to records from C. 

**a: {
b_records: [b1_id,b2_id,b3_id]
c_view_records: [b1_id,b2_id,b3_id]
}**

After hard deleting items in B collection in pocketbase UI, the proper record in C is also deleted, but I can still see record_ids when I download A record
 
e.g. after: **delete b1_id, b2_id**
it looks like this:

**a: {
b_records: [b3_id]
c_view_records: [b1_id,b2_id,b3_id]
}**

and not like this:

**a: {
b_records: [b3_id]
c_view_records: [b3_id]
}**

My temporary solution is to run a side script that controls whether all b_view_records really existin C. If not I overwrite the b_view_records by existing ids.

It would be nice if I have this automated controlling system integrated.

**Comment by ganigeorgiev** [comment] 2023-07-26 12:19
Could you export your collections configuration as JSON (Admin UI > Settings > Export collections)?

**Comment by ganigeorgiev** [comment] 2023-07-26 14:18
After some thinking I've decided to allow references to view collections **only** from other views.

The more I think on it the more edge cases show up and I'm not sure they can be resolved in a performant manner. Even if we somehow simulate materialized views with triggers (_which could be very complicated if the view query is constructed from subqueries or expressions_), the problem with the dynamic view ids still remains.

Existing relations to views from non-view collections will be converted with a system migration to `json`/`text` fields. It would be a minor web APIs breaking change since the direct `expand` will no longer work but no one has reported the problem previously so I doubt that there are too many projects that have defined relation fields to views.

**I'll consider tomorrow to push a "fix" in the `develop` branch and to prepare it as part of the upcoming v0.17.0 release (_most likely at the end of the this week or the week following it_).**

For your use case, you can try to apply the suggested change at the end of the [previous comment](https://github.com/pocketbase/pocketbase/issues/3000#issuecomment-1651754970) or restructure your DB.

**Comment by Zehir** [comment] 2023-07-26 18:09
I run in the exact same problem and there is also this case : 
With your sample data, if the view C is having a `where` clause to filter B record.
When you edit a value in a B record to filter out the record in C.
You end up in the same case where A have references to removed record of C.

So it's not only the delete operation that could cause this issue

**Comment by ganigeorgiev** [comment] 2023-07-27 13:06
I've submitted a "fix" in the `develop` branch that disallows relation to views from non-view collections.

It is restricting but until a different solution is found I think it is better than having a broken/unexpected behavior.

**Closed by ganigeorgiev** 2023-07-27 13:06 UTC

**Comment by McBucek** [comment] 2023-07-29 10:31
The reason for such a solution is if I have e.g. a collection "Order"
order: 
{
price,  worker_cost, order_date, client_info, worker_info, worker_feedback, client_feedback
}

and 3 type of users: Admin (can see all info about an order), worker (who can see just the information related to him - worker_info and can write worker_feedback), client (who can see information related to him - price, order_date, client_info, and can write client_feedback).

So one solution is: view collections (order_client_view, order_worker_view) that filter data for client and worker and contains all info related to them - each of them can write to core Order (only to field restricted to their roles) and can view filtered data in related View collection (it is nice it has same ID as the core Order).

Other solutions can be to keep only common data in the core and create specified base collections that are related to the core where are specific info to each role. But then there are more relations, collections, and more "expand" commands which can grow even more if there are more other cases in the database like this one.

The best is to have a filter command, that filters data from the core Order and returns it to each user depending on their role. But it must be programmed on the BE side. At that moment we should also program some auth functions on the BE, that control user credentials and then get data from the database filter and retrieve to the user. And because we are not really experienced in authentication on the BE side and PB has really nice API that keeps all the FE safe, we don't want to "touch it" :D. 

*The best would be to get data based on a role directly by filter function - but I can´t find info about that in the documentation. I see that I can only create a rules that restrict some actions and some filter records I can see https://pocketbase.io/docs/api-rules-and-filters/ . But I can´t see how to make a rule to return only some part of a record data if e.g. **pb.collection('order').getOne('order1id')** returns {worker_info, worker_feedback}
