### ISSUE TITLE
Suggestion: Show user name in User Field

### ISSUE THREAD

**Issue by 12Tall** [pocketbase/pocketbase#374] opened 2022-09-02 08:59 UTC
Hello, 
I love this awesome tool! 🍭🍭🍭And I also made a very simple GUI with python webview. <https://github.com/12Tall/pocketbase-py-gui>
but I meet an issue while using it - I just can not find the image of Admin avatar[win11]. 😂
and here is a little advice that if we can show the username to instead the unique id? I think it makes more sense for common users 

![image](https://user-images.githubusercontent.com/29416757/188103014-92146e23-09d9-4da0-8c5e-2e4967cfaa55.png)

**Comment by ganigeorgiev** [comment] 2022-09-02 09:17
About the missing images - PocketBase uses relative paths to load the embedded assets and it seems that the python webview is unable to load them for some reason. Could you inspect the 404 errors and post here here the paths that the GUI is trying to load?

About the username/email - users don't have username and email could be optional in case OAuth2 provider that doesn't return an email address was used to create the user. I'll consider for a future version to add help tooltip that will load the full user json on hover for easier debugging, but for now this is a low priority because there are other planned changes related to the users (_I'll soon post a proposal for merging users and profiles into a single structure_).

**Comment by 12Tall** [comment] 2022-09-02 09:46
Hello @ganigeorgiev ,
Thanks for your quickly reply. I met the image missing issue in my browser as well. sorry my browser language is Chinese 😂. The following picture shows that it will request `http://127.0.0.1:8090/_/images/logo.svg` but the result svg file can not be rendered in `<img></img>` nor `<image></image>`. I tried in Edge and Firefox, none of them works, it's strange.

![image](https://user-images.githubusercontent.com/29416757/188112330-3a938eca-b295-4ca6-b7ce-5f56a6b28883.png)

**Comment by ganigeorgiev** [comment] 2022-09-02 10:18
Hm, from the screenshot it seems that the static SVG files are detected as `Content-Type: document/ContetDrawDIAGRAM` instead of `Content-Type: image/svg+xml`.

I cannot reproduce the issue on my Windows 10 VM 21H2 Evaluation edition. Unfortunatelly I'm not able to test it on Windows 11 with my current VirtualBox setup and I'm not sure if this is some recent change.

I also cannot find information about the `document/ContetDrawDIAGRAM` mimetype. Do you have any drawing software that may have changed the default system registry? Could you try running the executable on a different windows instance?

**Comment by 12Tall** [comment] 2022-09-02 10:19
I think I find the reason: cause I installed ConceptDraw on my machine, and the response `Content-Type` of logo and avatar will be set to `Content-Type: document/ConceptDrawDIAGRAM`. but this operation will not be applied to the image file I uploaded. 

![image](https://user-images.githubusercontent.com/29416757/188118676-d1229857-7618-4ca9-baaa-f5e41509f999.png)

**Comment by ganigeorgiev** [comment] 2022-09-02 10:39
@12Tall Yep, this is probably due to some interference with 3rd party software.

The uploaded svg files are loaded as `image/svg+xml` because it is forced by the `/files/` api when requesting files with `.svg` extension.

The static embedded files on the other hand, are served with the default Go static net/http handler which, as it happen on Windows, it seems to use the system mimetype registry.

I'll close the issue for now, but if someone else experiencing similar problem, please let me know and I'll investigate it further.

As a workaround, we can manually set the mimetype for the embedded static files but I want to avoid that if possible.

In my opinion, this should be reported to ConceptDraw to investigate because any other software that relies on the svg mimetype from the system registry will be affected.

**Comment by 12Tall** [comment] 2022-09-02 10:40
Yes, After I changed the registry`Content Type = image/svg+xml` in `\HKEY_CLASSES_ROOT\.svg`. Seems all is fine. THANKS! 👍

**Closed by ganigeorgiev** 2022-09-02 10:39 UTC
