### ISSUE TITLE
Importing collections fails because of View Collections

### ISSUE THREAD

**Issue by ttofis** [pocketbase/pocketbase#2044] opened 2023-03-12 02:10 UTC
Importing Collections through JSON files on a clean pocketbase installation fails due to the data validations of the SQL request for View Collections.

The error it provides is it not being able to find the collection that you are looking for, even though it will be created by the JSON you provided.

A workaround I've been using is deleting my View Collections, importing, and then re-importing everything with the View Collections included.

I am guessing in situations where a View Collection requests data from another View Collection, that won't work. Maybe the SQL rules should be evaluated after all of the tables have been created?

Thanks for this amazing project!

**Comment by ganigeorgiev** [comment] 2023-03-12 10:24
I found the culprit. The view is actually evaluated after the collections insertion, but the problem is that the view query relies not on the collection entries but on their related record tables, which at the moment are synced at the last step of the import.

I'll push a fix sometime later today and will update the tests.

This could also explain reported issue in https://github.com/pocketbase/pocketbase/issues/2012.

**Comment by ganigeorgiev** [comment] 2023-03-12 15:55
Should be fixed in [v0.13.3 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.13.3).

Note that in case of a view referencing another view the order of the imported collections still could matter because there is no easy way to partially validate the views (the view create query is either persisted or not).
This is not an issue with the `base` and `auth` collections because the integrity checks are performed after their related record tables are created/modified.

**Closed by ganigeorgiev** 2023-03-12 15:55 UTC

**Comment by ttofis** [comment] 2023-03-12 17:40
Excellent! Thanks for the quick fix!
