### ISSUE TITLE
UI Glitch in dashboard

### ISSUE THREAD

**Issue by vigneshksaithal** [pocketbase/pocketbase#4492] opened 2024-03-05 17:03 UTC
<img width="247" alt="image" src="https://github.com/pocketbase/pocketbase/assets/60360863/5fd9b0fc-4b19-4abe-9c5b-51314ec64b07">

As you can see from above image, when clicked on the user icon in logs page it shows this glitch.

**Comment by ganigeorgiev** [comment] 2024-03-05 17:31
The issue seems to be reproducible only on Safari, at least based on my tests with Browserstack (locally works fine with Chrome 122 and Firefox 123).

My browserstack 1min free trial has expired but will try to find a way to debug it sometime later this week.

**Comment by ganigeorgiev** [comment] 2024-03-05 17:45
I've submitted a fix for the offending z-index in `master`. It will be part of the next minor v0.22.3 release.

**Closed by ganigeorgiev** 2024-03-05 17:45 UTC

**Comment by vigneshksaithal** [comment] 2024-03-05 18:03
@ganigeorgiev Browserstack is free for opensource projects, I just saw now.
<img width="494" alt="image" src="https://github.com/pocketbase/pocketbase/assets/60360863/0f61e30f-e418-4ce4-bd98-9836738521c4">
