### ISSUE TITLE
PB does not export fields in every collection

### ISSUE THREAD

**Issue by monstajoe2002** [pocketbase/pocketbase#1708] opened 2023-01-29 17:23 UTC
I believe the JSON File should also contain the fields created in every collection instead of entering in the fields again

**Comment by ganigeorgiev** [comment] 2023-01-29 18:54
I'm closing the issue because I'm not able to reproduce it (_if I'm understanding it correctly in the first place_).

The generated collections export from "Admin UI > Export collections" contains all the defined collection schema fields. Note that `id`, `created`, `updated` and the other system fields are not part of the collection's schema and are created automatically based on the collection type.

If the above is not what you were asking, feel free to provide more details and I'll investigate it.

**Closed by ganigeorgiev** 2023-01-29 18:54 UTC

**Comment by monstajoe2002** [comment] 2023-01-29 21:01
I mean if i export the schema and import it again, all the data in every collection is not included

**Comment by ganigeorgiev** [comment] 2023-01-29 21:03
The export and (the generated automigrations) doesn't handle data migrations.
Export/import of data will be eventually handled in #48.
