### ISSUE TITLE
authWithOAuth2 is not working in v0.10.0

### ISSUE THREAD

**Issue by arslanastral** [pocketbase/pocketbase#1291] opened 2022-12-18 08:01 UTC
`POST http://127.0.0.1:8090/api/collections/users/auth-with-oauth2`

In my Firefox console the above endpoint is not returning a response and just hangs when using `v0.10.0` but works fine on `v0.9.2` (also tried with chrome but same thing). `--debug` is also not showing anything useful

To test for any integration issue on my client I used the [example](https://pocketbase.io/docs/authentication/#web-oauth2-integration) that is provided on pocketbase docs but the problem still persists.

I also tried downgrading and found that OAuth is working till this commit: e964b019c24b4ba7e3445576a77179678d765a63 and stops working if I build using this: b9e257d2b1cd3f99941e7229c9bb820e2cd21fb3

#### Environment
Go Version: go1.19.4 linux/amd64
PocketBase: v0.10.0
OS: WSL2
OAuth Providers: Google & GitHub

**Comment by ganigeorgiev** [comment] 2022-12-18 10:08
The bug should be fixed in [v0.10.1](https://github.com/pocketbase/pocketbase/releases/tag/v0.10.1).

The hang was caused by a deadlock when rollbacking a "nested" transaction. Technically it is not nested because go sql/db doesn't support it out of the box yet (https://github.com/golang/go/issues/7898) and we do a hacky workaround with reusing the outer transaction context. Previously this worked because we were always starting a new db connection, but that's not the case with the split db pool and once a transaction (inner or outer) is rollbacked or  committed, the tx connection need to be discarded.

I've added a unit test to check the "nested" tx scenario. In the future I'll consider a more non-hacky workaround for the nested transactions.

If after the upgrade you are still experiencing the same issue, please let me know and I'll try to investigate it more thoroughly.

**Closed by ganigeorgiev** 2022-12-18 10:08 UTC
Labels: bug
