### ISSUE TITLE
Realtime fails when behind nginx proxy

### ISSUE THREAD

**Issue by jeffmikels** [pocketbase/pocketbase#488] opened 2022-09-16 05:08 UTC
I'm using the Dart client, and the realtime query from the README works fine when I authenticate with the backend using `http://IP_ADDRESS:9020` but it doesn't receive updates, and no errors are thrown when pocketbase is behind an nginx https proxy.

Here's my server block from nginx:

```nginx
# BEGIN POCKETBASE
# Upgrade WebSocket if requested, otherwise use keepalive
map $http_upgrade $connection_upgrade_keepalive {
	default upgrade;
	''      '';
}
server {
    listen 443 ssl;
    server_name [SERVER_NAME_REDACTED];

    location / {
        proxy_pass http://localhost:9020;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect default;

        # allow websocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

This configuration works fine for other websocket-based apps I'm using like self-hosted mattermost and others, but it seems to break the realtime updates from pocketbase.

Am I doing something wrong here?

**Comment by jonafeucht** [comment] 2022-09-16 05:12
Can you try adding `proxy_buffering off;` and see if that fixes it?

**Comment by ganigeorgiev** [comment] 2022-09-16 05:18
Yes, disabling `proxy_buffering` should fix it - you could also check https://github.com/pocketbase/pocketbase/discussions/480#discussioncomment-3657640.

But this is not ideal and it would be nice to have buffering disabled only for the realtime endpoint and therefore I'll add [`X-Accel-Buffering: no`](https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering) as a response header in the code, so that it doesn't require user to manually configure it in nginx.

_btw. @jeffmikels you don't need the upgrade headers stuff, because PocketBase is using server-sent events (sse) for the realtime subscriptions._

**Comment by ganigeorgiev** [comment] 2022-09-16 08:45
I've added the `X-Accel-Buffering` header in the [v0.7.3 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.7.3) so disabling the buffering globally shouldn't be necessary anymore.

@jeffmikels I'll close the issue, but if you are still having troubles with the realtime subscriptions, please let me know and I'll investigate it more thoroughly.

**Closed by ganigeorgiev** 2022-09-16 08:45 UTC

**Comment by jeffmikels** [comment] 2022-09-16 12:06
> Yes, disabling `proxy_buffering` should fix it - you could also check https://github.com/pocketbase/pocketbase/discussions/480#discussioncomment-3657640.

Yes, that was my exact situation. I should have searched discussions and not just issues!

**Comment by xrd** [comment] 2022-09-21 13:13
I'm still having some issues with realtime. I'm not sure if this is a client issue, or a server side issue.

Here is what I see in the JS console. I left it open overnight. Isn't it the case that I should see a new call to `/realtime` earlier than I do? It looks like nothing has occurred in 5 hours or so (look at the date in the JS console and the timestamp on the response header of the last `/realtime` request).

![realtime-issues](https://user-images.githubusercontent.com/17064/191513160-07317290-0e8d-44cf-8937-36ccacdef333.png)

My nginx config definitely has proxy_buffering off as you can see below. I'm using dokku, and not sure if there is more here to look at. dokku is basically nginx proxy + app running inside a docker container. 

```
$ dokku nginx:show-config | grep buffering
    proxy_buffering off;
```

Full config:

```

server {
  listen      [::]:80;
  listen      80;
  server_name publicdo-db-pb.tixfu.com pb.public.do; 
  access_log  /var/log/nginx/publicdo-db-pb-access.log;
  error_log   /var/log/nginx/publicdo-db-pb-error.log;

  include /home/dokku/publicdo-db-pb/nginx.conf.d/*.conf;
  location / {
    return 301 https://$host:443$request_uri;
  }

}

server {
  listen      [::]:443 ssl http2;
  listen      443 ssl http2;
  
  server_name publicdo-db-pb.tixfu.com pb.public.do; 
  access_log  /var/log/nginx/publicdo-db-pb-access.log;
  error_log   /var/log/nginx/publicdo-db-pb-error.log;

  ssl_certificate           /home/dokku/publicdo-db-pb/tls/server.crt;
  ssl_certificate_key       /home/dokku/publicdo-db-pb/tls/server.key;
  ssl_protocols             TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers off;

  keepalive_timeout   70;
  

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://publicdo-db-pb-8090;
    http2_push_preload on; 
    proxy_http_version 1.1;
    proxy_read_timeout 60s;
    proxy_buffer_size 4096;
    proxy_buffering off;
    proxy_buffers 8 4096;
    proxy_busy_buffers_size 8192;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-Start $msec;
    
  }

  
  include /home/dokku/publicdo-db-pb/nginx.conf.d/*.conf;

  error_page 400 401 402 403 405 406 407 408 409 410 411 412 413 414 415 416 417 418 420 422 423 424 426 428 429 431 444 449 450 451 /400-error.html;
  location /400-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 404 /404-error.html;
  location /404-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 500 501 503 504 505 506 507 508 509 510 511 /500-error.html;
  location /500-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }

  error_page 502 /502-error.html;
  location /502-error.html {
    root /var/lib/dokku/data/nginx-vhosts/dokku-errors;
    internal;
  }
}

upstream publicdo-db-pb-8090 {

  server 172.17.0.38:8090;
}


```

**Comment by ganigeorgiev** [comment] 2022-09-21 13:47
@xrd Hm, going through the nginx documentation, maybe only the [`keepalive_time` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#keepalive_time) is the reason for connection drop because by default is 1h. Another possibility is cancellation from client-side (eg. for example the browser dropping the connection) if it was suspended or similar.

I'm not really sure what could be the issue for that. Based on the logs screenshot, the reconnect sequence seems ok to me:
- 1 GET /api/realtime for establishing the SSE
- 1 preflight for the /api/realtime/ cors
- 1 POST /api/realtime for subscription submissions

The strange thing in the above screenshot is that the reconnect stopped for some reason and I'm not sure why exactly. You could try inspecting the last GET /api/realtime request to see whether it is actually still running or it is closed.

**Comment by xrd** [comment] 2022-09-21 15:15
Thanks for the notes. 

I think my confusion stems from what the correct final realtime POST call should look like. Does it have data in the response? It is empty when I use network inspector, and I'm not sure if this is correct.

It is **not** a socket connection, right? 

I'm unsure how to reason about what the correct state of the realtime request is when using SSE. 

I was experimenting with `proxy_read_timeout 999999;` as well, but this is not necessary now that we have `X-Accel-Buffering:no` (I am using a recent version of pocketbase).

**Comment by xrd** [comment] 2022-09-21 15:17
The last GET request says "connection closed." It has data, but nothing past that does. Is that normal?

![get-request-realtime](https://user-images.githubusercontent.com/17064/191543577-78aca167-289f-4bd7-b37b-8fdf822cb2fd.png)

**Comment by ganigeorgiev** [comment] 2022-09-21 15:22
@xrd On second thought, I doubt that the issue is caused by `keepalive_time` directive, because if you didn't receive any message for more than 5 minutes (even if you have higher limits in your nginx config), the server will automatically close the connection and the client will make an attempt to reconnect with a clean state.

**Or in other words - you'll never have idle connections that will last longer than 5 minutes.**

So there is something else going on here.

So far I wasn't able to reproduce the issue locally. I've started 2 servers (with and without nginx) and everything seems ok, at least for now. I'll leave them run for a couple more hours to check if there are some browser limits that I'm not aware of.

**Comment by xrd** [comment] 2022-09-21 15:24
Thanks so much for looking at this. For now, I'll probably just proactive re-subscribe to the realtime socket after 5 minutes inside the JS client.
