### ISSUE TITLE
Unique index / constraint for custom tables are not working

### ISSUE THREAD

**Issue by mbecker** [pocketbase/pocketbase#190] opened 2022-07-21 21:00 UTC
Hey,

I think I've found a bug for the DB migrations part to create a `unique` field which is not created at all in sqlite (and therefore not working by inserting a new record).

The schema migration files looks as follows:
```go
func init() {
	m.Register(func(db dbx.Builder) error {
		// add up queries...
		// inserts the system profiles collection
		// -----------------------------------------------------------
		profileOwnerRule := fmt.Sprintf("%s = @request.user.id", models.ProfileCollectionUserFieldName)
		collection := &models.Collection{
			Name:       ActivityCollectionName,
			System:     false,
			CreateRule: &profileOwnerRule,
			ListRule:   &profileOwnerRule,
			ViewRule:   &profileOwnerRule,
			UpdateRule: &profileOwnerRule,
			Schema: schema.NewSchema(
				&schema.SchemaField{
					Name:     models.ProfileCollectionUserFieldName,
					Type:     schema.FieldTypeUser,
					Unique:   false,
					Required: true,
					System:   false,
					Options: &schema.UserOptions{
						MaxSelect:     1,
						CascadeDelete: true,
					},
				},
				&schema.SchemaField{
					Name:     ActivityId,
					Type:     schema.FieldTypeNumber,
					Options:  &schema.NumberOptions{},
					Required: true,
					Unique:   true,
				},
				...
```

My expectation with the param `Unique: true` is that only 1 x record with that field can be created. Or, on other words, the sqlite index `unique` is created for this field. 

I can add multiple records with the same param for `ActivityId`. The sqlite index `unique` is not created.

This shows DBWeaver for the private table `_users` and the index `unique` for the field `email`:

<img width="969" alt="Screenshot 2022-07-21 at 22 49 16" src="https://user-images.githubusercontent.com/26771/180312786-95598ac5-cdf3-4081-ad78-1e867787a19f.png">

This shows the DBWeaver for the table `activities` (created in the migration file) and no index `unique`:

<img width="904" alt="Screenshot 2022-07-21 at 22 52 04" src="https://user-images.githubusercontent.com/26771/180313123-c1d4a3ed-a6e3-41a8-ad7f-ec5f059aadc7.png">

This shows the PocketBase UI with detailed information for the fields (the field `activity` is labeled as `unique`) and in the background you see multiple records with the same `activityid`:

<img width="1203" alt="Screenshot 2022-07-21 at 22 54 15" src="https://user-images.githubusercontent.com/26771/180313739-b04b1030-c904-4e20-bfdf-cc187483f711.png">

In the repo I see some test for checking the `uniqueness` for the private tables (like `_users`) but not for custom tables.

** Update
Sorry, I didn't look enough into the tests. Test as the following clearly defines scenarios for `unique`:

https://github.com/pocketbase/pocketbase/blob/79265016495c2514a2589b3c79696d9b9e9a8baf/forms/validators/record_data_test.go#L46 

However, for me the migration files does not create the index `unique`.

Hope this helps and I've not done any mistakes. Thanks!

Just for reference, the following is the code to insert the records in an hook event:
```go
rec := models.NewRecord(activityCollection)
		rec.SetDataValue(migrations.ProfileCollectionUserId, userId)
		rec.SetDataValue(migrations.ActivityId, a.Id)
		rec.SetDataValue(migrations.ActivityExternalId, a.ExternalId)
		rec.SetDataValue(migrations.ActivityUploadId, a.UploadId)
		rec.SetDataValue(migrations.ActivityAthleteId, a.Athlete.Id)
		rec.SetDataValue(migrations.ActivityName, a.Name)
		rec.SetDataValue(migrations.ActivityDistance, a.Distance)
		rec.SetDataValue(migrations.ActivityMovingTime, a.MovingTime)
		rec.SetDataValue(migrations.ActivityElapsedTime, a.ElapsedTime)
		rec.SetDataValue(migrations.ActivityTotalElevationGain, a.TotalElevationGain)
		rec.SetDataValue(migrations.ActivityType, a.Type)
		rec.SetDataValue(migrations.ActivityStartDate, a.StartDate)
		rec.SetDataValue(migrations.ActivityStartDateLocal, a.StartDateLocal)
		rec.SetDataValue(migrations.ActivityTimeZone, a.TimeZone)
		rec.SetDataValue(migrations.ActivityStartLatLng, startLatLng)
		rec.SetDataValue(migrations.ActivityEndLatLng, endLatLng)
		rec.SetDataValue(migrations.ActivityMapId, a.Map.Id)
		rec.SetDataValue(migrations.ActivityMapPolyline, a.Map.SummaryPolyline)
		rec.SetDataValue(migrations.Activity, a)
		err = app.Dao().SaveRecord(rec)
		if err != nil {
			fmt.Println(err)
			continue
		}
```

**Comment by ganigeorgiev** [comment] 2022-07-22 05:32
I'm not sure that I understand what actually the issue is. Constraints and indexes are two different things.

When you mark a field as "Unique" it will add a **unique constraint** (not index) on application level, aka. you won't be able to submit a **new record** with the same value. The same apply for the **Required** constraint.
PocketBase will not change existing user defined data if it is not safe to modify them, aka. if you already have inserted duplicated records, they will remain in the database and the next time you try to edit them and error will be shown that the value already exist.

About the above code - it doesn't do any data validations. If you need validations, the use the [`forms.RecordUpsert` struct](https://github.com/pocketbase/pocketbase/blob/master/forms/record_upsert.go).

PocketBase currently doesn't manage add indexes for the created fields - there is already a task to define simple 1 column/field indexes from the Admin UI in the [roadmap](https://github.com/orgs/pocketbase/projects/2).

**Comment by ganigeorgiev** [comment] 2022-07-22 07:17
My remark about the constraints vs indexes was to outline the differences between them - while for most dbms adding a unique/foreign key constraint will also add a corresponding index they are usually different things. But that doesn't matter for PocketBase, as you've noted, because we are managing the constraints on application level.

I think I understand now your use case, but the way you are implementing is incorrect.

Executing `CREATE UNIQUE INDEX activities_activityid_IDX ON activities (activityid)` in a `OnBeforeServe` hook will run the query every time when your application starts (eg. on process restart).

The Dao is operating directly with the database (aka. doing select, insert, update, delete statements) and it doesn't perform data validations ("exception" to this is when handling the cascade delete operations to ensure that the app is not left in a broken state).

I thinks forms are more suitable for your use case - they can read/load data from the request (or any other external source), validate it and persist (internally they uses the Dao).

So as an alternative, instead of adding a unique sql index, you could replace your `Dao().Save` call with the form one:
```
err := forms.NewRecordUpsert(app, rec).Save()
```
The above should return an error if you have duplicated entries and your field is marked as "Unique".

**I completely agree with you that the current code documentation is not enough and we need to create some guides that explain more clearly the internals and their differences.** This is exists in the roadmap and will be handled in the near future but I'm currently focusing on stabilizing the PocketBase API since adding more advanced documentation and examples will be hard to keep in sync due to the frequent internal changes.

I'll close the issue for now, but if you are still having difficulties trying to use PocketBase as framework, please let me know and I'll try to help (it also helps me to understand better how users are interpreting the code and whether the current approaches should be reworked).

**Closed by ganigeorgiev** 2022-07-22 07:17 UTC

**Comment by mbecker** [comment] 2022-07-22 07:52
Hi,

i think it's as follows:
```go
// Works as expected with errors: 'activityid: Value must be unique.'
err := forms.NewRecordUpsert(app, rec).Submit()

// method "Save" does not exist
err := forms.NewRecordUpsert(app, rec).Save()
```
Thanks!

Maybe a not related question for that. Does a "submit" (create / update) via the forms triggers the realtime subscription? I would like to have a realtime subscription for new records.

**Comment by ganigeorgiev** [comment] 2022-07-22 08:05
Oops, sorry. Yes, it should be `Submit()`, not `Save()` (I'll update it in the comments above).

About the realtime subscriptions - currently Create/Update realtime events are send only after the API calls, but I'll make sure to update it in v0.4.0 for consistency with the Delete action (it was recently changed because of #109).

For now, if you want to trigger the realtime subscription events for create/update manually, as a workaround you could trigger the hooks that broadcast the message:
```go
event := &core.RecordCreateEvent{Record: rec}
app.OnRecordAfterCreateRequest().Trigger(event)

event := &core.RecordUpdateEvent{Record: rec}
app.OnRecordAfterUpdateRequest().Trigger(event)
```
But keep it mind that the above will change in v0.4.0 and the hooks will be replaced with `onModelAfterCreate` and `OnModelAfterUpdate`.

**Comment by mbecker** [comment] 2022-07-22 08:12
Holy! It's working! Thanks for your time and very detailed responses. Awesome work!

**Comment by ganigeorgiev** [comment] 2022-08-11 09:32
@mbecker Just to let you know that with [v0.4.0 release](https://github.com/pocketbase/pocketbase/releases) changing a record with the Dao will trigger automatically a realtime create/update event so there is no longer need to trigger them manually.

**Comment by mxmaxime** [comment] 2023-01-19 21:10
Hi,
Just by curiosity, why did you choose to have contraints on application level?

If we want to use it as a framework, it can cause issues.
For example, If I have a relationship field, let's say `device_id`, it won't perform the check to see if the device exists if I use the dao.

```go
// I use directly the model to insert a new record
m := &Motions{
  DeviceID: "that doesn't exist"
// ....
}
dao.Save(m)
// it works :(
``` 

I need to use forms right? Seems a bit weird to not leverage sql constraints / foreign keys ect.

**Comment by ganigeorgiev** [comment] 2023-01-19 21:21
Dao doesn't perform validations. If you need validations use the forms.
Custom models are just an option (_and they need a little more refinement_). For most of the cases the `Record` model should be the preferred way to query and modify your data.

> Just by curiosity, why did you choose to have contraints on application level?

Because the constraints are "dynamic" and doesn't require modifying the schema. Unique indexes (and regular indexes in general) will be handled in #1466 and #544.
