### ISSUE TITLE
Unable to delete individual files with "-" suffix. 

### ISSUE THREAD

**Issue by tevintchuinkam** [pocketbase/pocketbase#1826] opened 2023-02-10 21:00 UTC
I'm trying to delete delete  a single file from a multiple file upload field but it does not seem to work. I just get back a 200 for the patch request and see that nothing was actually deleted. 

Deleting all the files by using `null` works tho. 

Any suggestions? 
Thanks in advance.

**Comment by ganigeorgiev** [comment] 2023-02-10 21:08
I've just tested it locally and it is working fine for me (there are also [integration tests](https://github.com/pocketbase/pocketbase/blob/master/forms/record_upsert_test.go#L155) that confirms the behavior).

Here is an example with the JS SDK:

```js
await pb.collection("example").update("RECORD_ID", {
    // you can also pass an array for deleting multiple files
    "myFileField-": "abc_Fdt6aN3pdZ.png"
})
```

Are you sending json or multipart/form-data? Could you provide a code sample?

**Comment by ganigeorgiev** [comment] 2023-02-10 21:39
I'm closing the issue since I'm not able to reproduce it. I've tested it locally with both json and miltipart/form-data requests and it is working fine for me.

I'm not sure what could be the cause of the issue in your case. Make sure that you are using PocketBase v0.11+.

Feel free to provide more details how you are sending the request and I'll investigate it further.

**Closed by ganigeorgiev** 2023-02-10 21:39 UTC
