### ISSUE TITLE
Drag-and-drop of table fields don't work in safari

### ISSUE THREAD

**Issue by peterhijma** [pocketbase/pocketbase#2567] opened 2023-05-24 18:24 UTC
These drag and drop buttons don't work in safari. Nothing happens, it seems. In chrome it works fine. 

<img width="137" alt="Scherm­afbeelding 2023-05-24 om 20 20 53" src="https://github.com/pocketbase/pocketbase/assets/29425150/cc5bad89-9b60-46b2-9723-314eca38e031">

(PS: Thanks for creating this inspiring tool)

**Comment by ganigeorgiev** [comment] 2023-05-24 20:26
I don't have Safari to test it but the issue is also reproducible in Gnome Web (_which is based on older WebKit version that Safari uses_).

It seems that WebKit is a little more strict and doesn't allow dummy/blank elements as drag placeholder, aka. the following is causing Safari/Gnome Web to fail silently:

```js
e.dataTransfer.setDragImage(document.createElement("div"), 0, 0);
```

I've pushed a fix in `master` and will be available with the next minor v0.16.3 release (_I'll not rush a release since it is fairly minor and it is not a blocker_).

**Closed by ganigeorgiev** 2023-05-24 20:26 UTC
