### ISSUE TITLE
Upload image (file field) failed

### ISSUE THREAD

**Issue by agmeeder** [pocketbase/pocketbase#3189] opened 2023-08-25 07:20 UTC
There is a table with a file field where you can upload a jpg or png file. Since version 0.17.6 I get an error:

2023/08/25 09:12:45 failed to upload all files: [file 0: blob (key "qvblhsps7r1x944/5av4nlb3tj86lac/test_HIoH4Cygpe.jpg") (code=Unknown): rename C:\Users\ALEXAN~1\AppData\Local\Temp\test_HIoH4Cygpe.jpg.177e8ed74dc5d584.tmp d:\projects\wie-is-wie-server\pb_data\storage\qvblhsps7r1x944\5av4nlb3tj86lac\test_HIoH4Cygpe.jpg: The system cannot move the file to a different disk drive.]

Any idea what could be the cause?

**Comment by ganigeorgiev** [comment] 2023-08-25 10:44
I'm closing the issue as I'm not able to reproduce it locally on a Windows 10 VM with the prebuilt PocketBase v0.17.6 executable.

If your issue is not caused from using a gocloud.dev v0.33.0 dependency, please provide more details whether the prebuilt executable is used or you are using the PocketBase Go package as part of your own Go program (if the latter, please also attach your go.mod if possible) and I'll try to investigate it further.

**Closed by ganigeorgiev** 2023-08-25 10:44 UTC

**Comment by agmeeder** [comment] 2023-08-25 10:52
Thank you @ganigeorgiev for your very quick reaction. The problem is solved with your suggestion.
