### ISSUE TITLE
Too Many Files open serving static directory

### ISSUE THREAD

**Issue by DigNZ** [pocketbase/pocketbase#4524] opened 2024-03-08 00:22 UTC
My code has this in order to serve the files from the public directory:

```
// Add support for all other endpoints to server public dir
app.OnBeforeServe().Add(func(e *core.ServeEvent) error {
    // serves static files from the provided public dir (if exists)
    e.Router.GET("/*", apis.StaticDirectoryHandler(os.DirFS("./public"), false))
    return nil
})

```

After a while of running I start getting these errors:
`http: Accept error: accept tcp [::]:8090: accept4: too many open files; retrying in 1s`

And the static site starts returning a 404 error - the pocketbase admin and API continue to function normally. Restarting my executable resolves the issue and the static files (site frontend) works again for a couple of days. 

I've been running this for around 7-8 months and it has only started happening this week and happens daily. I don't know if it is a recent update or higher than before traffic that has tipped it over the edge.

Research into that error lead me here:
https://stackoverflow.com/questions/56880388/accept-tcp-accept4-too-many-open-files-retrying-in-1s
and here:
https://stackoverflow.com/questions/37454236/net-http-server-too-many-open-files-error

A quick browse through the pocketbase code seems to imply that DefaultClient is used and maybe that is causing this problem?

**Comment by ganigeorgiev** [comment] 2024-03-08 05:51
Without steps to reproduce, I'm not sure how to help you.

There are no changes to the static files serving in the recent releases and I don't see how it is related to the linked discussions or the `http.DefaultClient`.

`too many open files` error could happen for a lot of reasons and it is difficult to pinpoint the exact culprit without having access to the environment or knowing your normal workload. See also https://pocketbase.io/docs/going-to-production/#increase-the-open-file-descriptors-limit.

It is possible to be caused by forgotten file descriptor somewhere by at first glance I can't seem to find such.

If you think that it is a PocketBase issue, feel free to provide steps to reproduce (eg. what is the result of `ulimit -a` and how many requests triggers it) and I'll try to investigate it but as of now there is no actionable item here and I'll close the issue.

**Closed by ganigeorgiev** 2024-03-08 05:51 UTC
