### ISSUE TITLE
Crash: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tonyhart7** [pocketbase/pocketbase#2245] opened 2023-04-07 22:13 UTC
Pocketbase instance crashing while doing nothing 

Yesterday I just installed pocketbase instance in cloud like usually via dockerfile, new instance fresh install fresh database just filling out bunch of schema and testing it works 

today its crashes with this log 

~~~
2023/04/05 20:45:46 Server started at http://0.0.0.0:8080/
➜ REST API: http://0.0.0.0:8080/api/
➜ Admin UI: http://0.0.0.0:8080/_/
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7d3169]
goroutine 3565 [running]:
database/sql.(*Rows).close.func1()
/opt/hostedtoolcache/go/1.20.2/x64/src/database/sql/sql.go:3287 +0x29
database/sql.withLock({0x243b740, 0xc0003ce000}, 0xc0007c0700)
/opt/hostedtoolcache/go/1.20.2/x64/src/database/sql/sql.go:3405 +0x8c
database/sql.(*Rows).close(0xc00015c000, {0x24358c0, 0x30d3420})
/opt/hostedtoolcache/go/1.20.2/x64/src/database/sql/sql.go:3286 +0x16d
database/sql.(*Rows).awaitDone(0xc0007c07d0?, {0x2443fd8, 0xc00015e000}, {0x0?, 0x0?})
/opt/hostedtoolcache/go/1.20.2/x64/src/database/sql/sql.go:2940 +0xd2
created by database/sql.(*Rows).initContextClose
/opt/hostedtoolcache/go/1.20.2/x64/src/database/sql/sql.go:2924 +0x158
~~~

I have 2 instance running this one crash while the other one (0.12.3) already run for 1 month old perfectly fine 
from the looks of it, I assuming its Go Garbage Collector doing something wrong

**Comment by ganigeorgiev** [comment] 2023-04-07 22:16
I'm not sure how to reproduce it. Please provide a minimal reproducible repo or at least details about your setup:

- What PocketBase version you are using?
- Are you using the prebuilt executables or as part of your own Go program?
- If you are using PocketBase as framework could you share your main file and how you initialize the application?

**Comment by tonyhart7** [comment] 2023-04-07 22:23
> I'm not sure how to reproduce it. Please provide a minimal reproducible repo or at least details about your setup:
> 
> * What PocketBase version you are using?
> * Are you using the prebuilt executables or you are embedding PocketBase as part of your own Go program?
> * If you are using PocketBase as framework could you share your main file and how you initialize the application?

- pocketbase version 0.14.2
- prebuild
- I make 1 collection of images with title,description and file images as schema then connect it via http and it just it

using these dockerFile. I dnt see anything wrong because its works yesterday and now it crash while no one use it (collection schema has only 1 account and it just me who can access it)

~~~
FROM alpine:latest

ARG PB_VERSION=0.14.2

RUN apk add --no-cache \
    unzip \
    # this is needed only if you want to use scp to copy later your pb_data locally
    openssh

# download and unzip PocketBase
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/

EXPOSE 8080

# start PocketBase
CMD ["/pb/pocketbase", "serve", "--http=0.0.0.0:8080"]
~~~

**Comment by ganigeorgiev** [comment] 2023-04-07 22:27
Hm, I don't see anything unusual in the above.

It could be a disk or OOM error, I'm not sure. Are there any more details to the stacktrace?

**Comment by tonyhart7** [comment] 2023-04-07 22:41
> Hm, I don't see anything unusual in the above.
> 
> It could be a disk or OOM error, I'm not sure. Are there any more details with the stacktrace?

that's the only log, this is reproduce schema maybe it can help. 

~~~
[
    {
        "id": "_pb_users_auth_",
        "name": "users",
        "type": "auth",
        "system": false,
        "schema": [
            {
                "id": "users_name",
                "name": "name",
                "type": "text",
                "system": false,
                "required": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "users_avatar",
                "name": "avatar",
                "type": "file",
                "system": false,
                "required": false,
                "options": {
                    "maxSelect": 1,
                    "maxSize": 5242880,
                    "mimeTypes": [
                        "image/jpeg",
                        "image/png",
                        "image/svg+xml",
                        "image/gif",
                        "image/webp"
                    ],
                    "thumbs": null
                }
            }
        ],
        "indexes": [],
        "listRule": "id = @request.auth.id",
        "viewRule": "id = @request.auth.id",
        "createRule": "",
        "updateRule": "id = @request.auth.id",
        "deleteRule": "id = @request.auth.id",
        "options": {
            "allowEmailAuth": true,
            "allowOAuth2Auth": true,
            "allowUsernameAuth": true,
            "exceptEmailDomains": null,
            "manageRule": null,
            "minPasswordLength": 8,
            "onlyEmailDomains": null,
            "requireEmail": false
        }
    },
    {
        "id": "ydbb2iyv448f0t9",
        "name": "images",
        "type": "base",
        "system": false,
        "schema": [
            {
                "id": "i9lj2rsa",
                "name": "image_variable_name",
                "type": "text",
                "system": false,
                "required": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "4arv3bxq",
                "name": "image_description",
                "type": "text",
                "system": false,
                "required": false,
                "options": {
                    "min": null,
                    "max": null,
                    "pattern": ""
                }
            },
            {
                "id": "vrz80vtb",
                "name": "image_link",
                "type": "file",
                "system": false,
                "required": true,
                "options": {
                    "maxSelect": 1,
                    "maxSize": 52428800,
                    "mimeTypes": [
                        "image/jpeg",
                        "image/png",
                        "image/svg+xml",
                        "image/gif",
                        "image/webp"
                    ],
                    "thumbs": [
                        "480x720"
                    ]
                }
            }
        ],
        "indexes": [],
        "listRule": "",
        "viewRule": "",
        "createRule": "@request.auth.id != \"\"",
        "updateRule": null,
        "deleteRule": null,
        "options": {}
    }
]
~~~

**Comment by ganigeorgiev** [comment] 2023-04-07 22:47
I just tested it locally with both v0.14.2 and v0.14.3 with your collections configuration and I'm not able to reproduce the goroutine panic.

> that's the only log, this is reproduce schema maybe it can help.

The above stacktrace unfortunately is not enough to pinpoint the issue. Usually there would more than one goroutine panic. Since we don't call explicitly the `database/sql` drive, aka. something external has triggered it.

For now I'm closing the issue as it is not reproducuble, but feel free to create a minimal reproducible repo or paste a more detailed stack trace and I'll try to investigate it.

**Closed by ganigeorgiev** 2023-04-07 22:47 UTC
