### ISSUE TITLE
Unable to delete rows in collection when using "+"characters in customId

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [pocketbase/pocketbase#1552] opened 2023-01-09 18:41 UTC
When using special characters like `+` in a customId for a record one is later unable to delete the record via the API since trying to call this:

![image](https://user-images.githubusercontent.com/36411819/211382679-a054d61a-ef82-4d41-bdd9-f5bc4691d3a1.png)

results in API calls like this:

![image](https://user-images.githubusercontent.com/36411819/211382949-7c522d32-e20d-4b3c-8597-4862501b3857.png)

Backend was hosted on Fly, the delete calls where submitted via the admin ui.
Let me know if you need more info 🙂

**Comment by BunnyTheLifeguard** [comment] 2023-01-09 18:51
Hm weird, apparently %2B is the escaped + sign, still it results in a 404 🤔

**Comment by ganigeorgiev** [comment] 2023-01-09 19:18
This is caused by the url encoded characters because internally we try to match the record id with the `c.PathParam("id")` value, but for some reason instead of the decoded value the raw version is returned. I'm not sure whether this is an issue with echo or if it is related to https://github.com/golang/go/issues/33596. I'll investigate it in more details and will add an integration test to verify the decoding.

**Comment by BunnyTheLifeguard** [comment] 2023-01-09 19:40
Thanks, otherwise I would suggest to simply validate url safe characters:

https://stackoverflow.com/a/695469

**Comment by ganigeorgiev** [comment] 2023-01-09 19:44
Validating just the characters is not enough since the above could happen with other user defined url parameters.

It will be fixed soon, but I'll need to first find out whether this is an issue with echo or it is just an implementation detail and we'll have to fix it in our code.

**Comment by ganigeorgiev** [comment] 2023-01-09 20:39
This is fixed in `master` and will be available with the next bugfix release sometime later this week.

It turn out that it is an implementation detail of echo but it is configurable so we just had to enable the option.

**Closed by ganigeorgiev** 2023-01-09 20:39 UTC
