### ISSUE TITLE
Can't save file(s) on version 0.22.0

### ISSUE THREAD

**Issue by burggraf** [pocketbase/pocketbase#4471] opened 2024-03-02 04:15 UTC
After upgrading an application to 0.22.0 I'm unable to save an avatar image to the users collection.  It throws an error in the UI: "Failed to update record."  If I downgrade the app to 0.21.3, it works fine.

The same issue occurs if I try to upload the avatar image from my app.

**Comment by ganigeorgiev** [comment] 2024-03-02 04:24
If you are using S3, it is possible to be related to the `aws-sdk-go-v2` upgrade.

Could you paste the more detailed error log from the _Admin UI > Logs_ and/or start the executable with `--dev`?
If you use S3 - what is the name of the provider?

**Comment by ganigeorgiev** [comment] 2024-03-02 07:08
I've tried with both the local filesystem and S3 (Wasabi, MinIO playground and GCS) and I'm not able to reproduce the issue.

The only thing different related to the filesystem abstraction in v0.22.0 is the upgrade to `aws-sdk-go-v2`, which has slightly different headers sign implementation that may not be compatible with some S3 providers.
We currently has only exception in regards to that for GCS and when the standard domain is used, aka. `storage.googleapis.com`: https://github.com/pocketbase/pocketbase/blob/35d7b5f056ee27f3604afc377571ec705fc49bda/tools/filesystem/filesystem.go#L73-L77.

I'll close the issue for now as there is not enough details to reproduce it, but feel free to elaborate on your setup and I'll try to investigate it further.

**Closed** 2024-03-02 07:09 UTC

**Comment by burggraf** [comment] 2024-03-02 13:10
Looks like my mistake -- I had S3 turned on accidentally in the project, you're right.
