### ISSUE TITLE
Admin panel is not opening on Windows

### ISSUE THREAD

**Issue by FeodorFitsner** [pocketbase/pocketbase#6] opened 2022-07-07 16:03 UTC
While trying to open Admin panel at http://localhost:8090/_/ on Windows 11 I'm getting blank page and the following error in a browser console:

```
index.944ee0db.js:1 
        
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
```

Browser: Microsoft Edge 103.0.1264.49

**Comment by ganigeorgiev** [comment] 2022-07-07 16:18
Hm, that's strange.

I'll try later installing Edge on Linux to see if I it could reproduce it.

**Comment by FeodorFitsner** [comment] 2022-07-07 16:21
Thanks! I remember fixing that with adding a MIME type for `.js`: https://github.com/flet-dev/flet/blob/main/server/server/server.go#L71

**Comment by enxoco** [comment] 2022-07-07 18:18
Seems to be working fine for me.  I am also on Windows 11 and the same build of Microsoft Edge.  I originally launched it in Brave and set up a couple collections.  Not sure if that would make a difference.

**Comment by ganigeorgiev** [comment] 2022-07-07 18:25
I've installed and tried Edge on Linux but wasn't able to reproduce it, so the issue is not browser related and it's most likely platform dependent.

There is a very similar issue reported in the golang repo - https://github.com/golang/go/issues/32350

I'm currently downloading a Windows 11 VM to test it locally, but it'll take some time.

**Comment by ganigeorgiev** [comment] 2022-07-07 20:14
I've just tested it on a Windows 10 VM 17.17134 with installed latest edge and chrome and everything seems OK.

I wasn't able to test on a Windows 11 VM, because the only [official image](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/) I could find was ~20GB and for my location it'll takes more than 2 hours to download.

@FeodorFitsner Could you share your exact Windows version?

_In any case, it seems that a fix already landed in go but probably would be available with go1.19 (this August) - https://github.com/golang/go/commit/52f68efa45a34e60e8fc5a2ad5fc124a865ac2a4_

**Comment by FeodorFitsner** [comment] 2022-07-07 21:54
Windows 11 Version 10.0.22000.739

**Comment by matt-clegg** [comment] 2022-07-08 09:40
I'm getting the same issue in Windows 10 21H2 19044.1766 in Firefox 102.0.1 (64-bit).

**Comment by ganigeorgiev** [comment] 2022-07-08 10:38
@FeodorFitsner, @matt-clegg when you find time, could you check also with the v0.1.1 binary - https://github.com/pocketbase/pocketbase/releases/download/v0.1.1/pocketbase_0.1.1_windows_amd64.zip ?
(it is built with go1.19.0-beta.1 that supposedly is expected to "fix" the issue).

**Comment by matt-clegg** [comment] 2022-07-08 11:47
@ganigeorgiev Just tested the v0.1.1 binary on Windows 10 and it seems to be working now! However it did seem to take around 25 seconds for the admin dashboard to become accessible. I was stuck on an "Unable to connect" screen in Firefox.

**Comment by ganigeorgiev** [comment] 2022-07-08 15:31
@FeodorFitsner Hm, this should be something with  the local network configuration. Are you using a VPN?

**Comment by FeodorFitsner** [comment] 2022-07-08 15:33
Please nevermind, it's on my router. Strange, that previous binary worked - must be something changed in Go 1.19 regarding that. Could you point me to a place in your code where you start the server with localhost binding? I'd like to do a repro. Thanks!

**Comment by ganigeorgiev** [comment] 2022-07-08 15:35
@FeodorFitsner  You could find the code here - https://github.com/pocketbase/pocketbase/blob/master/cmd/serve.go#L77

If you don't have localhost in your /etc/hosts file, you could also try starting the application with `--http="127.0.0.1:8090"`

**Comment by FeodorFitsner** [comment] 2022-07-08 15:47
Indeed, in `C:\Windows\System32\drivers\etc\hosts` I have localhost section commented:

```
# localhost name resolution is handled within DNS itself.
#       127.0.0.1       localhost
#       ::1             localhost
```

Starting with ` --http="127.0.0.1:8090"` did the trick and I'm able to see Admin panel now!

**Comment by ganigeorgiev** [comment] 2022-07-08 16:22
@matt-clegg Just downloaded and installed an offocial Eveluation Windows 10 21H2 VM and I' not able to reproduce the slow start up time - the application seems to be loading normally to me (aka. under a second).

I'll close the issue for now and will add a note in the documentation/readme to use go 1.19 on window, but if someone else still is experiencing issues, feel free to comment and I'll reopen it.

**Closed by ganigeorgiev** 2022-07-08 16:22 UTC
Labels: bug

**Comment by waterdrw** [comment] 2022-08-12 07:37
i'm serve in ubuntu 16.04 :) 

MX record result here
![image](https://user-images.githubusercontent.com/912132/184306442-3f3de91a-6176-43fd-a05d-996a7a3701c3.png)

i serve --http="127.0.0.1" --debug mode. but no errors or warnings

**Comment by ganigeorgiev** [comment] 2022-08-12 07:41
@waterdrw Please post in the related discussion https://github.com/pocketbase/pocketbase/discussions/298 since you'll have better visibility and other users may be able to help.
