### ISSUE TITLE
Enable S3, Delete collection loading infinite

### ISSUE THREAD

**Issue by hungcrush** [pocketbase/pocketbase#1400] opened 2022-12-27 17:31 UTC
Hi~
Sorry. I have infinite loading when I turn on S3, turn off it's ok. Could you give me some suggest where can I check and fix it?

Sorry if i upset you. I'm really love PocketBase and Golang. I'm trying to be pro like you 😬

**Comment by ganigeorgiev** [comment] 2022-12-27 17:41
What do you mean by "infinite loading" and when do you experience it, during delete?

In "Admin UI > Settings > File storage" do you have a green checkmark saying that the s3 config is OK?

If yes, could you provide an example structure of your collection (Admin UI > Settings > Export collections)?

In "Admin UI > Settings > File storage" do you have a green checkmark saying that the s3 config is OK?

In any case, you can start PocketBase with `--debug` and see if there is a console error.

_Also please make sure to test with the latest [v0.10.4 release](https://github.com/pocketbase/pocketbase/releases/tag/v0.10.4)._

**Comment by ganigeorgiev** [comment] 2022-12-27 18:51
@hungcrush I've just tested it locally with the Vultr S3 compatible Object Storage offering and it is working fine for me.

There was an issue in v10.2 and older versions related to the s3 upload, but it should be fixed in the latest release.

If after the upgrade you are still experiencing issues, please provide more details and I'll investigate it more thoroughly.

**Comment by hungcrush** [comment] 2022-12-28 00:08
Hi @ganigeorgiev I just download official version on pocketbase.io
 
![Uploading CleanShot 2022-12-28 at 
<img width="882" alt="CleanShot 2022-12-28 at 07 07 07@2x" src="https://user-images.githubusercontent.com/8098916/209738306-0ef2cbcb-bbe7-49d3-a016-33208900e5e1.png">
07.07.00@2x.png…]()

And this is my S3 config:

<img width="868" alt="CleanShot 2022-12-28 at 07 07 50@2x" src="https://user-images.githubusercontent.com/8098916/209738340-e5773e44-dd37-4ab4-9d62-fcc6afe75683.png">

If you need please give me your email, i will send you my config

**Comment by ganigeorgiev** [comment] 2022-12-28 06:32
_You can attach your collections configuration as json here or send it to `support @ pocketbase.io`._

I suspect this is a permission issue or incorrect S3 configuration (eg. do you really need the "Force path-style addressing"?)

The only way I was able to reproduce it was due to invalid S3 config because currently we don't have an explicit timeout for the S3 operations (it is in the roadmap and will be added together with the individual request timeouts).

Please check:

- Does uploading a file works?

- Do you have any special access/permission policies for your S3 storage/account (eg. disallowing deletion)?

**Comment by hungcrush** [comment] 2022-12-28 08:04
Hi @ganigeorgiev 
I found the problem.

> I suspect this is a permission issue or incorrect S3 configuration (eg. do you really need the "Force path-style addressing"?)

I tried to disable this and change from
`https://cf-simple-s3-origin-cloudfrontfors3-713801267216.s3.amazonaws.com` to `https://s3.amazonaws.com`

It works well now.

> Does uploading a file works? 
=> Upload well in both cases

Thank you so much.

**Comment by ganigeorgiev** [comment] 2022-12-28 08:07
Thank you for confirming.

Proper configurable timeouts will be added in the near future.

I'll consider in the next release to improve the automated S3 config check so that it can throw an error when saving the S3 settings.

**Closed by ganigeorgiev** 2022-12-28 08:07 UTC
