### ISSUE TITLE
More information on how to logout users (Oauth2)

### ISSUE THREAD

**Issue by Bastian1110** [pocketbase/pocketbase#332] opened 2022-08-20 18:30 UTC
I'm trying out pocketbase for a school project, so far everything has been amazing!
I feel like there should be more documentation on how to logout users. I have tried to use the function: 
```
client.authStore.clear()
```
However, when I use it, the isValid attribute of AuthStore becomes false, but when I try to make a new login it takes me directly to the redirect URL, without going through the provider page (Google).
Is this an Oauth issue? Or should I clear the localStorage too?

**Comment by ganigeorgiev** [comment] 2022-08-20 18:48
I'm not sure if I understand the described issue.

When you clear the `authStore`, you "logout" the user **only from your PocketBase app**.
But your user may still be "signed-in" in the OAuth2 provider's domain because of a cookie (we cannot delete foreign domain cookies).

Or in other words - PocketBase doesn't have control and will not logout you from your Google account.

I'll close the issue since this should be expected behavior, but if the above is not what you are describing, please provide a little more detail on your OAuth2 handing and I'll reopen it.

**Closed by ganigeorgiev** 2022-08-20 18:48 UTC
